export const schema = {
  models: {
    Mawwal: {
      name: 'Mawwal',
      fields: {
        id: {
          name: 'id',
          isArray: false,
          type: 'ID',
          isRequired: true,
          attributes: [],
        },
        fullPath: {
          name: 'fullPath',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        filename: {
          name: 'filename',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        category: {
          name: 'category',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        createdAt: {
          name: 'createdAt',
          isArray: false,
          type: 'AWSDateTime',
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: 'updatedAt',
          isArray: false,
          type: 'AWSDateTime',
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: 'Mawwals',
      attributes: [
        {
          type: 'model',
          properties: {},
        },
        {
          type: 'auth',
          properties: {
            rules: [
              {
                allow: 'public',
                operations: ['create', 'update', 'delete', 'read'],
              },
            ],
          },
        },
      ],
    },
    Photo: {
      name: 'Photo',
      fields: {
        id: {
          name: 'id',
          isArray: false,
          type: 'ID',
          isRequired: true,
          attributes: [],
        },
        filename: {
          name: 'filename',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        test: {
          name: 'test',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        fullPath: {
          name: 'fullPath',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        category: {
          name: 'category',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        createdAt: {
          name: 'createdAt',
          isArray: false,
          type: 'AWSDateTime',
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: 'updatedAt',
          isArray: false,
          type: 'AWSDateTime',
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: 'Photos',
      attributes: [
        {
          type: 'model',
          properties: {},
        },
        {
          type: 'auth',
          properties: {
            rules: [
              {
                allow: 'public',
                operations: ['create', 'update', 'delete', 'read'],
              },
            ],
          },
        },
      ],
    },
    Article: {
      name: 'Article',
      fields: {
        id: {
          name: 'id',
          isArray: false,
          type: 'ID',
          isRequired: true,
          attributes: [],
        },
        publisherEN: {
          name: 'publisherEN',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        publisherAR: {
          name: 'publisherAR',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        categoryEN: {
          name: 'categoryEN',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        categoryAR: {
          name: 'categoryAR',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        date: {
          name: 'date',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        year: {
          name: 'year',
          isArray: false,
          type: 'Int',
          isRequired: false,
          attributes: [],
        },
        month: {
          name: 'month',
          isArray: false,
          type: 'Int',
          isRequired: false,
          attributes: [],
        },
        day: {
          name: 'day',
          isArray: false,
          type: 'Int',
          isRequired: false,
          attributes: [],
        },
        filename: {
          name: 'filename',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        fileType: {
          name: 'fileType',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        parentPath: {
          name: 'parentPath',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        fullPath: {
          name: 'fullPath',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        title: {
          name: 'title',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        createdAt: {
          name: 'createdAt',
          isArray: false,
          type: 'AWSDateTime',
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: 'updatedAt',
          isArray: false,
          type: 'AWSDateTime',
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: 'Articles',
      attributes: [
        {
          type: 'model',
          properties: {},
        },
        {
          type: 'auth',
          properties: {
            rules: [
              {
                allow: 'public',
                operations: ['create', 'update', 'delete', 'read'],
              },
            ],
          },
        },
      ],
    },
  },
  enums: {},
  nonModels: {},
  codegenVersion: '3.4.4',
  version: '6ec17d74b5f717c1bf9864a2369ed26f',
};
